citylist = ['Chicago', 
            'Paris', 
            'Valparaiso', 
            'New York', 
            'Washington DC', 
            'Tel Aviv', 
            'London', 
            'Singapore', 
            'Boston', 
            'Amsterdam', 
            'Sao Paulo', 
            'San Francisco', 
            'Copenhagen', 
            'Mexico City', 
            'Sydney', 
            'Taipei', 
            'Rio De Janeiro', 
            'Bangkok', 
            'Stockholm', 
            'Hong Kong', 
            'Berlin', 
            'Philadelphia', 
            'Seattle', 
            'Melbourne', 
            'Dublin', 
            'Milan', 
            'Los Angeles', 
            'Guadalajara', 
            'Moscow', 
            'Barcelona', 
            'Rome', 
            'Belo Horizonte', 
            'Helsinki', 
            'Tokyo', 
            'Santiago', 
            'Portland', 
            'Prague', 
            'Atlanta', 
            'Toronto', 
            'Bucharest', 
            'Lisbon', 
            'Kyoto', 
            'Montreal', 
            'Madrid', 
            'Kiev', 
            'Warsaw', 
            'Glasgow', 
            'Minneapolis', 
            'Denver', 
            'Munich', 
            'Bratislava', 
            'Zagreb', 
            'Cape Town', 
            'Johannesburg', 
            'Houston', 
            'Gaborone']

catelist = ['safety', 'lively', 'wealthy', 'beautiful', 'depressing', 'boring']

for city in sorted(citylist): 
    catelinklist = []
    filename = 'pp2_' + '%20'.join(city.split(' ')) + '_boring' + '.html'
    catelink = f' - [{city}](https://luxin-tian.github.io/Scoring-Neighborhoods-on-the-Earth/boring/{filename})'
    print(catelink)